name: Build and Release Tauri App

on:
  push:
    branches:
      - main  # 触发打包的分支
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [macos-latest, windows-latest]  # 构建多平台

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.4.1'  # 选择你的 Node.js 版本

      - name: Install dependencies
        run: yarn install

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Install Tauri CLI
        run: cargo install tauri-cli --locked

      - name: Build Tauri App
        run: yarn tauri build

      - name: Clean Cargo cache
        run: cargo clean

      - name: Regenerate Cargo.lock
        run: cargo generate-lockfile

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tauri-build-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/macos/*.app
            src-tauri/target/release/bundle/windows/*.exe
